### ISSUE TITLE
Traceback (most recent call last):   File "/usr/bin/crlfsuite", line 33, in <module>     sys.exit(load_entry_point('CRLFsuite==2.0', 'console_scripts', 'crlfsuite')())   File "/usr/bin/crlfsuite", line 22, in importlib_load_entry_point     for entry_point in distribution(dist_name).entry_points   File "/usr/lib/python3.9/importlib/metadata.py", line 542, in distribution     return Distribution.from_name(distribution_name)   File "/usr/lib/python3.9/importlib/metadata.py", line 196, in from_name     raise PackageNotFoundError(name) importlib.metadata.PackageNotFoundError: CRLFsuite

### ISSUE THREAD

**Issue by memmedrehimzade** [Nefcore/CRLFsuite#2]
Traceback (most recent call last):
  File "/usr/bin/crlfsuite", line 33, in <module>
    sys.exit(load_entry_point('CRLFsuite==2.0', 'console_scripts', 'crlfsuite')())
  File "/usr/bin/crlfsuite", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 542, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 196, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: CRLFsuite

**Comment by Raghavd3v** [comment]
Hi @memmedrehimzade,

Can you tell me the exact command that you have supplied while this error occurred?

**Comment by Elsfa7-110** [comment]
@Nefcore

any command for ex
crlfsuite -h

![Screenshot 2022-06-12 222226](https://user-images.githubusercontent.com/26175351/173252200-617e3d59-063f-4b04-b8c8-eb4058df6a12.png)

**Comment by Raghavd3v** [comment]
@Elsfa7-110,

Have you executed the installation command: `sudo python3 setup.py install`, if the error still occurs then just uninstall the tool using `sudo pip uninstall crlfsuite` and now reinstall the latest version of the tool because you're using the older version.

**Comment by Elsfa7-110** [comment]
@Nefcore 

the same happend with the latest version

**Comment by Raghavd3v** [comment]
@Elsfa7-110,

This error occurs when the package is not installed properly, probably it's not a issue or bug it's just a installation problem, Copy & Paste the following commands:

* sudo apt-get update && apt-get upgrade
* sudo apt-get install python3
* sudo apt-get install python3-pip
* pip install setuptools
* git clone https://github.com/Nefcore/CRLFsuite.git
* cd CRLFsuite
* sudo python3 setup.py install 

*Make sure that no error occurs while running these commands.*

**If the error still occurs then just make a screen recording while installing the tool and send it on nefcore.sec@gmail.com**
