### ISSUE TITLE
Getting error while adding user-agent

### ISSUE THREAD

**Issue by z3dc0ps** [Nefcore/CRLFsuite#6]
![image](https://user-images.githubusercontent.com/61974788/181331810-259b08a4-74b6-4222-96d8-25caac504d4b.png)

**Comment by Raghavd3v** [comment]
Hi @z3dc0ps,

Thanks for reporting this issue, it's fixed now (<a href="https://github.com/Nefcore/CRLFsuite/commit/d80844a9f96f6f1e1e5272a43a392058781621e1">d80844a</a>)
